version: '3'
services:
  telecomdb:
    container_name: telecomdb
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "dbPassword"
      POSTGRES_USER: "dbUser"
    volumes:
      - ./database/initsql/database_init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  app:
    container_name: telecom
    image: golang:1.19.3-alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/go/src/vinbigdata
    working_dir: /go/src/vinbigdata
    command: >
      sh -c "go run cmd/telecom/main.go"
    depends_on:
      - telecomdb
    restart: always
